### PR TITLE
:sparkles: Show specific error messages for invitation token failures

### LINKED ISSUE #9220: :sparkles: Improve error UX on error reporting on the invtation token errors
## Summary

Right now independently of the issue, we show a generic error:

Image

But internally:
- we know that if you try to accept an invitation that does not match your currently logged-in email, fails.
- we know when invitation is expired
- we know when invitation is corrupted token

## Expect improvement

- Show to the user proper error when the currently logged email does not match the invitation
- Show to the user proper error when the token is really expired and (when is expired)
- Show to the user proper error when token is just invalid token.

### PR DESCRIPTION
**Pull request by jack-stormentswe**
## Related Ticket

Closes #9220

## Summary

When accepting a team invitation, the UI currently shows the same generic error message regardless of why the invitation failed. The backend already distinguishes three failure modes:

1. The currently logged-in email does not match the invitation's email
2. The invitation token has expired
3. The invitation token is corrupted / invalid

This PR maps each backend error code to its own user-facing message and recovery hint, so users immediately understand whether they need to switch accounts, request a new invitation, or contact the inviter.

## Why this matters

Penpot is the open-source design tool aimed at everyone, including people who have never managed team invitations in a SaaS product before. A generic "something went wrong" leaves the user stuck — they don't know whether to try again, log out, ask for a fresh invite, or give up. Specific, actionable error messages make the recovery path obvious without requiring the user to read documentation or contact support, which is exactly the kind of polish that keeps first-time
users from bouncing.

## Steps to Reproduce

**Setup:** Send a team invitation to `alice@example.com`.

**Case A — Email mismatch:**
1. Log in as `bob@example.com` (different account).
2. Open the invitation link.
3. Observe a generic error with no hint that the issue is the logged-in account.

**Case B — Expired token:**
1. Wait for the invitation TTL to elapse.
2. Open the invitation link as the correct user.
3. Observe the same generic error with no hint to request a new invite.

**Case C — Invalid / corrupted token:**
1. Manually mangle the token in the invitation URL.
2. Open the link.
3. Observe the same generic error with no hint that the link itself is malformed.

**Expected:** A different, actionable message in each case.
**Actual:** Same generic error.

## Solution

**1. Map backend error codes to specific user-facing messages**
[frontend/src/app/main/ui/auth/verify_token.cljs](frontend/src/app/main/ui/auth/verify_token.cljs)
- The team-invitation accept flow already receives a typed error response from the backend (`:invitation-email-mismatch`, `:invitation-token-expired`, `:invalid-token`).
- Replace the catch-all error branch with a `case` that surfaces a specific message for each known code. Unknown codes fall back to the existing generic message so future error types stay safe.

**2. Add three new translation strings**
[frontend/translations/en.po](frontend/translations/en.po)
- `errors.invitation-email-mismatch` — "This invitation was sent to a different email. Log out and sign in with the invited account, or ask for a new invitation."
- `errors.invitation-token-expired` — "This invitation has expired. Ask the team owner to send you a new one."
- `errors.invitation-token-invalid` — "This invitation link is not valid. Make sure you copied the full link, or ask for a new invitation."

**3. Verify the backend already returns distinct codes**
[backend/src/app/rpc/commands/teams.clj](backend/src/app/rpc/commands/teams.clj)
- Confirmed the relevant `accept-team-invitation` command raises three distinct `ex/raise` codes already — no backend change needed.

## Design Notes

- **No behavior change for unknown error codes.** The existing generic message stays as the default, so any future error path is still handled gracefully.
- **No new modal or dialog** — the messages render in the same inline error region as today, so visual placement is unchanged.
- **No backend change** — backend already returns the typed codes; the frontend was just collapsing them.

## Checklist

- [ ] Email-mismatch case shows a "wrong account" message with a switch-account hint
- [ ] Expired-token case shows an "expired, request a new invitation" message
- [ ] Invalid-token case shows a "link is not valid" message
- [ ] Unknown error codes still render the generic fallback
- [ ] Translation keys added to en.po
- [ ] Tested in Chrome and Firefox
- [ ] CHANGES.md entry added

## Video to upload

**Case 1 — Email mismatch:**

https://github.com/user-attachments/assets/f5d2357a-7107-488f-b411-1b918d8d1ae8

**Case 2 — Invalid / corrupted token:**

https://github.com/user-attachments/assets/926ff632-219c-470c-96ca-14050f8eafb2

### CODE REVIEW

**Comment by jack-stormentswe** [comment]
Hi @niwinz
How are you? I opened this for #9220 whenever you have a moment to take a look. 
Happy to adjust direction if you'd prefer a different approach.
Appreciate.

File: frontend/src/app/main/ui/static.cljs [hunk 1]
```diff
@@ -67,10 +67,21 @@
...
+                   :email-mismatch "errors.invite-email-mismatch"
+                   :token-expired  "errors.invite-expired"
+                   "errors.invite-invalid")
+        desc-key (case reason
+                   :email-mismatch "errors.invite-email-mismatch.info"
+                   :token-expired  "errors.invite-expired.info"
+                   "errors.invite-invalid.info")]
+    [:> error-container* {}
+     [:div {:class (stl/css :main-message)} (tr main-key)]
+     [:div {:class (stl/css :desc-message)} (tr desc-key)]]))
```
Comment (niwinz) [inline frontend/src/app/main/ui/static.cljs]: This looks nice, but for statically analysis, it is better to have the `(tr "errors.invite-email-mismatch.info")` instead of `(tr some-variable)`
We have a script that analyzes the code and tracks the string usage. So i suggest refactoring this function in order to use `tr` with string literal instead a variable.

File: frontend/translations/en.po [hunk 2]
```diff
@@ -1545,6 +1545,22 @@ msgstr "Invite invalid"
 msgid "errors.invite-invalid.info"
 msgstr "This invite might be canceled or may be expired."
 
+#: src/app/main/ui/static.cljs
+msgid "errors.invite-expired"
+msgstr "This invitation has expired"
+
+#: src/app/main/ui/static.cljs
+msgid "errors.invite-expired.info"
+msgstr "Ask the team owner to send you a new invitation."
```
Comment (niwinz) [inline frontend/translations/en.po]: I think we should remove the `.info` from the key

File: frontend/translations/en.po [hunk 3]
```diff
@@ -1545,6 +1545,22 @@ msgstr "Invite invalid"
...
+
+#: src/app/main/ui/static.cljs
+msgid "errors.invite-email-mismatch"
+msgstr "This invitation is for a different email"
+
+#: src/app/main/ui/static.cljs
+msgid "errors.invite-email-mismatch.info"
```
Comment (niwinz) [inline frontend/translations/en.po]: The same

File: frontend/src/app/main/ui/auth/verify_token.cljs [hunk 4]
```diff
@@ -68,8 +68,15 @@
...
-        bad-token (mf/use-state false)]
+  (let [token            (get-in route [:query-params :token])
+        bad-token        (mf/use-state false)
+        ;; When the token failed, we keep the specific reason so the
+        ;; static page can show an actionable message instead of the
+        ;; generic "this invitation is invalid" copy. Reasons:
+        ;;   :token-expired   -> JWT past its :exp
+        ;;   :email-mismatch  -> invitation email != logged-in email
+        ;;   :invalid-token   -> corrupted / unknown / fallback
+        bad-token-reason (mf/use-state nil)]
```
Comment (niwinz) [inline frontend/src/app/main/ui/auth/verify_token.cljs:79]: I think we can reuse the `bad-token` or rename it to the `bad-token-reason` and populate it with a string. As string is logical true, we simplify it just to a single state hook.

**Comment by niwinz** [comment]
hey @jack-stormentswe 
Awesome, thanks.

I have posted some minor feedback.
In any case it is awesome, thanks :heart:

**Comment by jack-stormentswe** [comment]
Hi @niwinz 
Thanks for your kind feedback. ❤️ 
Agree with your proposal 👍  Will update asap.

File: frontend/src/app/main/ui/static.cljs (hunk 1 above)
Comment (davidv399) [reply frontend/src/app/main/ui/static.cljs]: Good catch - refactored. The function now uses a case over reason and calls tr with literal keys in each branch, so the i18n usage scanner can statically track every key. Falls back to the generic errors.invite-invalid (with its existing .info companion) for unknown reasons.

File: frontend/translations/en.po (hunk 2 above)
Comment (davidv399) [reply frontend/translations/en.po]: Done 👍

File: frontend/translations/en.po (hunk 3 above)
Comment (davidv399) [reply frontend/translations/en.po]: Done 👍

File: frontend/src/app/main/ui/auth/verify_token.cljs (hunk 4 above)
Comment (davidv399) [reply frontend/src/app/main/ui/auth/verify_token.cljs:79]: Good point - collapsed into a single bad-token-reason state.
Updated the docstring above the state to make the contract explicit.

**Comment by jack-stormentswe** [comment]
Hi @niwinz
Thanks for your previous feedback. ❤️
Done 👍

**Comment by niwinz** [comment]
Ready to merge, waiting CI

**Comment by jack-stormentswe** [comment]
Hi @niwinz 
CI test passed 👍
