### PR TITLE
Bugfixes

### LINKED ISSUE #1184: Can't select three digit hex code in color picker
**Describe the bug**
When I type the hex code 333 the color does not appear in the color picker.

**Screenshots**
image

**Desktop (please complete the following information):**

-   Big Sur 11.5.2
-   Safari Version 15.0 (16612.1.28.1, 16612)

### LINKED ISSUE #1186: Create component option missing from context menu for objects nested in component
**Describe the bug**
The 'create component' option is missing from the right click contextual menu for objects nested under a component. I am able to create a component out of the object using the shortcut 'cmd-k'

**To Reproduce**
1.  Right click an object that is part of a component in the layers menu
2.  Observe 'create component' option missing

**Expected behavior**
expect to see the option available

**Screenshots**
image

**Desktop (please complete the following information):**

-   big sur 11.5.2
-   Safari Version 15.0 (16612.1.28.1, 16612)

### LINKED ISSUE #1216: line end style dropdown is not fully visible
The dropdowns that select line end styles are going off the screen and last options are not visible and impossible to scroll to. Probably happens only on smaller screens (13'' MBP) and in cases when the browser window is not full screen. Also shadow options are displayed over this dropdowns.

**Steps to reproduce the behavior:**
1. Open Penpot (browser window should not be big, for example about 700px high)
2. Create a path object without closing it
3.  Add some fill color (optional, just reduces vertical space even more)
4.  In the Stroke options panel select either of the end style dropdowns
5.  **See that some options are off the screen it's impossible to scroll to see them**
6. Close the dropdown
7. Press "+" shadows panel and press 3 dots icon to open shadow options
8. **Open the end style dropdown again and see that shadow options panel is displayed over it**

**Expected behavior**
When the dropdown is open and off the screen user should be able to scroll to see all options. Other panels should not be displayed over dropdown.

**Screenshots**
Screen Shot 2021-09-15 at 16 03 04
Screen Shot 2021-09-15 at 16 02 36

**Desktop:**
-   OS: macOS Mojave
-   Browser: Firefox 92.0 (64-bit)

**Environment:**
design.penpot.app

### LINKED ISSUE #1219: Internal error when clicking on existing comment in comment list
**Describe the bug**
When I click on a comment in the comment list, the site throws an Internal error. I can return to the project easily by clicking Retry though.

**To Reproduce**
1. Insert a comment
2. Go to comment list
3. Click on comment

**Expected behavior**
I wanted to see an option menu so I could delete the comment from the comment list

**Desktop (please complete the following information):**

-   OS: Ubuntu
-   Browser: Firefox
-   Version: 92.0

**Environment (please complete the following information):**
Using SAAS at https://design.penpot.app.

**Additional context**
My friend has no such issue and he's running the Brave browser.

### LINKED ISSUE #1230: Typography asset does not list correct typeface after undo via history
**Describe the bug**
If one changes the typeface of a typography asset, and then proceeds to undo the change, the asset will show the last selected typeface as opposed to the *effective* typeface. This persists between reloads, and project changes.

**To Reproduce**
1. Create and apply a typography asset
2. Observe that text objects using that asset reflect the stated typeface
3. Change the typeface
4. Observe that text objects reflect changes
5. Access history, and revert the typeface change
6. Observe that text objects reflect the original typeface
7. Observe that the typography asset typeface selection *does not* reflect the original and effective typeface.

**Expected behavior**
Typography assets reflect the current and effective typeface for that asset.

**Screenshots**
Text showing incorrect typeface

In the above screenshot you will see that the selected text object has the 'Name' typography asset associated. The 'Name' asset indicates that [Goudy Bookletter 1911](https://www.theleagueofmoveabletype.com/goudy-bookletter-1911) is in use when *this could not be further from the truth*.

What is most frustrating about this is that I did not recall what typeface was in use originally, and had to use developer tools to retrieve it from the DOM.

**Desktop (please complete the following information):**

-   OS: Not applicable
-   Browser (e.g. chrome, safari): Chrome (embedded, nativefier) *and* Firefox
-   Version (e.g. 22): Not going to bother figuring out the equivalent chrome version, FF 91

**Environment (please complete the following information):**
SaaS 

**Additional context**

### LINKED ISSUE #1231: Text object clipping clashes with typeface geoemetry in some scenarios
**Describe the bug**
In a text object of fixed dimension, changing to right alignment may result in portions of the type being cut off.

**To Reproduce**
1. Create a text object and set typeface to *Cormorant Garamond*, variant *italic* (reg. weight)
2. Set contents of text object to something such as `~12:30` (what was used in this case, any text will likely work)
2. Resize text object to a fixed size
3. Select ragged right text alignment
4. Observe that rightmost letterform is cut off

**Expected behavior**
Right-most letterform will not be cut off

**Screenshots**
the text "~12:30" in italics with the "0" being partially obscured

**Desktop (please complete the following information):**

-   OS: Linux
-   Browser: Chrome

**Environment (please complete the following information):**
SaaS

### PR DESCRIPTION
**Pull request by Alotor**
Closes #1216 
Closes #1186 
Closes #1219 
Closes #1230
Closes #1231
Closes #1184

- Fix problem with overflow dropdown on stroke-cap [#1216](https://github.com/penpot/penpot/issues/1216)
- Fix menu context for single element nested in components [#1186](https://github.com/penpot/penpot/issues/1186)
- Fix error screen when operations over comments fail [#1219](https://github.com/penpot/penpot/issues/1219)
- Fix undo problem when changing typography/color from library [#1230](https://github.com/penpot/penpot/issues/1230)
- Fix problem with text margin while rendering [#1231](https://github.com/penpot/penpot/issues/1231)
- Fix problem with masked texts on exporting [Taiga #2116](https://tree.taiga.io/project/penpot/issue/2116)
- Fix text editor enter behaviour with centered texts [Taiga #2126](https://tree.taiga.io/project/penpot/issue/2126)
- Fix residual stroke on imported svg [Taiga #2125](https://tree.taiga.io/project/penpot/issue/2125)
- Add links for terms of service and privacy policy in register checkbox [Taiga #2020](https://tree.taiga.io/project/penpot/issue/2020)
- Allow three character hex and web colors in color picker hex input [#1184](https://github.com/penpot/penpot/issues/1184)
- Allow lowercase search for fonts [#1180](https://github.com/penpot/penpot/issues/1180)
- Fix group renaming problem [Taiga #1969](https://tree.taiga.io/project/penpot/issue/1969)
- Fix export group with shadows on children [Taiga #2036](https://tree.taiga.io/project/penpot/issue/2036)
- Fix zoom context menu in viewer [Taiga #2041](https://tree.taiga.io/project/penpot/issue/2041)
- Fix stroke caps adjustments in relation with stroke size [Taiga #2123](https://tree.taiga.io/project/penpot/issue/2123)
- Fix problem duplicating paths [Taiga #2147](https://tree.taiga.io/project/penpot/issue/2147)

### CODE REVIEW

File: frontend/src/app/main/ui/render.cljs [hunk 1]
```diff
@@ -25,9 +25,26 @@
...
    [rumext.alpha :as mf]))
 
+(defn bounds
+  [object objects]
+  (if (= :group (:type object))
+    (let [children-bounds
+          (into []
+                (comp  (map #(get objects %))
+                       (map #(bounds % objects)))
+                (:shapes object))]
```
Comment (niwinz) [inline frontend/src/app/main/ui/render.cljs:35]: Here you can avoid use `let` with `->`
Just a :lipstick: change.
