### PR TITLE
:tada: Add stroke to path

### LINKED ISSUE #9961: Add outline stroke to Paths
https://tree.taiga.io/project/penpot/us/2956

### Config flag

`stroke-path`

📜 DESCRIPTION
--------------

Expressed using the formula:

As a penpot user, I want to be able to outline the strokes of the paths I create.

### 👆 INTERACTION

When I have a shape that has a stroke, I may want to make that stroke a shape, so I want to have the ability to outline it.

We will have an option in the contextual menu that appears when right-clicking on the shape that contains the stroke, and it will show the option to outline stroke. 

### 🤔 UNKNOWNS AND CHALLENGES

When a shape has a fill, the conclusion of “outline stroke” will be two shapes, one with the fill and no stroke, and one with the stroke outlined and filled

### Technical limitations

This feature is available only under the new render.
It has been developed in this US https://tree.taiga.io/project/penpot/us/8536

Design: https://design.penpot.dev/#/workspace/cfd4ca10-ef85-11eb-a311-6a3557fe78ff/25659130-987d-11ec-a0a3-84d7741b7d65?page-id=25659131-987d-11ec-a0a3-84d7741b7d65 
External source: https://community.penpot.app/t/feature-request-outline-stroke-feature/1989
External source 2: https://github.com/penpot/penpot/issues/4099

### how to test

**Outline stroke on a basic shape with a stroke**

    Create a rectangle on the canvas.
    Add a stroke to it (e.g. 4px solid, any color).
    Right-click the shape to open the contextual menu.
    Click "Outline stroke".

Expected: The stroke is converted into a separate closed path/shape. The original shape's stroke is removed. The new stroke shape is visible and selectable on the canvas.

**Outline stroke on a path / vector shape**

    Draw a path using the pen tool (open or closed).
    Assign a stroke (e.g. 6px solid).
    Right-click and select "Outline stroke".

Expected: The stroke becomes a filled shape that accurately mirrors the stroke width and caps/joins of the original path. The original stroke property is cleared.

**Shape with multiple strokes**

    Create a shape and add two or more strokes with different widths/colors.
    Right-click and select "Outline stroke".

Expected: All strokes are outlined (one resulting shape per stroke). No crash. Result visually matches the original strokes.

**Undo after outline stroke**

    Perform the outline stroke action.
    Press Ctrl+Z (or Cmd+Z on Mac).

Expected: The shape returns to its original state with the stroke applied. The outlined shape is removed.

### PR DESCRIPTION
**Pull request by elenatorro**
### Summary

This PR adds the "stroke to path" feature only for the WASM render and when activating the `enable-stroke-path` config flag, since it still has to be tested.

### Steps to reproduce 

- Activate the config flag `enable-stroke-path`
- Create a shape
- Add a stroke
- Left click -> on context menu, click on "Stroke to path"

It should create a new path shape **for each stroke present in the shape**. It should work with all kinds of shapes.

[screen-recorder-wed-mar-18-2026-10-36-39.webm](https://github.com/user-attachments/assets/8e7d62e5-fccc-4601-9848-747aeede9dcb)

### Checklist

- [x] Choose the correct target branch; use `develop` by default.
- [x] Provide a brief summary of the changes introduced.
- [x] Add a detailed explanation of how to reproduce the issue and/or verify the fix, if applicable.
- [x] Include screenshots or videos, if applicable.
- [x] Add or modify existing integration tests in case of bugs or new features, if applicable.
- [ ] Refactor any modified SCSS files following the refactor guide.
- [x] Check CI passes successfully.
- [ ] Update the `CHANGES.md` file, referencing the related GitHub issue, if applicable.

### CODE REVIEW

**Comment by esaramago** [comment]
This is great! Thanks!

File: render-wasm/src/wasm/paths.rs [hunk 1]
```diff
@@ -235,6 +236,99 @@ pub extern "C" fn current_to_path() -> *mut u8 {
...
+                let path = Path::from_skia_path_accurate(final_path);
+                result = path
+                    .segments()
+                    .iter()
+                    .copied()
+                    .map(RawSegmentData::from_segment)
+                    .collect();
+            }
+        }
+    });
```
Comment (belen-albeza) [inline render-wasm/src/wasm/paths.rs:267]: For readability's sake, let's make our WASM API a bit "dumb" and extract this out of the wasm module into a method in the actual domain.

File: render-wasm/src/shapes/paths.rs [hunk 2]
```diff
@@ -114,6 +114,109 @@ impl Path {
         Path::new(segments)
     }
 
+    /// Like `from_skia_path` but properly converts conics to cubic beziers
+    /// (using Skia's conic-to-quad + quad-to-cubic elevation). Use this when
+    /// accurate curve conversion matters (e.g. stroke-to-path on circles).
```
Comment (belen-albeza) [inline render-wasm/src/shapes/paths.rs:119]: 🤯  TIL

File: frontend/playwright/ui/specs/stroke-to-path.spec.js [hunk 3]
```diff
@@ -0,0 +1,285 @@
...
+  await workspace.mockRPC(
+    "update-file?id=*",
+    "workspace/update-file-create-rect.json",
+  );
+  await workspace.goToWorkspace();
+  await workspace.waitForFirstRender();
+
+  await workspace.rectShapeButton.click();
+  await workspace.clickWithDragViewportAt(200, 200, 200, 150);
+  await workspace.waitForSelectedShapeName("Rectangle");
```
Comment (belen-albeza) [inline frontend/playwright/ui/specs/stroke-to-path.spec.js]: We could avoid this in every test (and therefore make the tests run faster) if we use a `get-file` fixture with a rect already on it.

**Review by belen-albeza — APPROVED** [review]
Works like a charm! Added two refactor suggestions in case you want to implement them.

File: render-wasm/src/shapes/paths.rs (hunk 2 above)
Comment (elenatorro) [reply render-wasm/src/shapes/paths.rs:119]: same 😂

File: render-wasm/src/wasm/paths.rs (hunk 1 above)
Comment (elenatorro) [reply render-wasm/src/wasm/paths.rs:267]: sure!! let me change this

File: frontend/playwright/ui/specs/stroke-to-path.spec.js (hunk 3 above)
Comment (elenatorro) [reply frontend/playwright/ui/specs/stroke-to-path.spec.js]: +1, I'll change it
